### ISSUE TITLE
Decoding Issue

### ISSUE THREAD

**Issue by boredom1234** [rondotcomYT/Infinity-Drive#3]
While trying to decode files a little bigger such as the original video "https://youtu.be/8I4fd_Sap-g" it pops up an error.

Traceback (most recent call last):
  File "C:\Users\ME\Desktop\Infinity-Drive\Infinity-Drive.py", line 125, in <module>
    density = int(bytes(int(binary[i:i+8], 2) for i in range(0, len(binary), 8)).decode('utf-8'))
ValueError: invalid literal for int() with base 10: '\x08\x00'

**Comment by rondotcomYT** [comment]
Interesting, thank you for pointing this out. It's most likely due to the fact that the decoding method for this repository wasn't built to be compatible with other projects, but still odd that It's having trouble processing the input, even If it would create a corrupted / incomplete file.

Will investigate this shortly.

**Comment by rondotcomYT** [comment]
This is most likely because of the fact that the decoding process for this project and the one [Infinity-Storage-Glitch](https://github.com/DvorakDwarf/Infinite-Storage-Glitch) uses are different, although perhaps I'll try and implement support for methods different projects use.

Useful feedback nonetheless, thank you for pointing this out :)
